# Generated by Django 3.0.5 on 2021-05-20 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id_process', models.IntegerField(default=100000000, primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('timeSlot', models.TimeField(auto_now=True)),
                ('id_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
