# Generated by Django 2.2.5 on 2021-05-27 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210528_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='zone',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G'), ('h', 'H'), (None, 'Khu Khác')], editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 11, 19, 0, 0)),
        ),
    ]
