# Generated by Django 2.2.5 on 2021-05-28 02:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210528_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='faculty',
            field=models.CharField(choices=[('CNTT', 'Công Nghệ Thông Tin'), ('KHDL', 'Khoa Học Dữ Liệu'), ('DTVT', 'Điện Tử Viễn Thông'), ('CNSH', 'Công Nghệ Sinh Học'), ('KT', 'Kiến Trúc'), ('XD', 'Xây Dựng'), ('CD', 'Cầu Đường'), (None, 'Ngành Khác')], max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 4, 17, 0, 0)),
        ),
    ]
