# Generated by Django 2.2.5 on 2021-05-28 03:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210528_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='confidence',
            field=models.PositiveSmallIntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 8, 6, 0, 0)),
        ),
        migrations.CreateModel(
            name='Unknown',
            fields=[
                ('unknown_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img_face', models.ImageField(null=True, upload_to='images/temps/')),
                ('confidence', models.PositiveSmallIntegerField(default=0, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Process')),
            ],
            options={
                'verbose_name': 'Unknown',
                'verbose_name_plural': 'Unknowns',
            },
        ),
    ]
