# Generated by Django 2.2.5 on 2021-05-28 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210528_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 11, 26, 0, 0)),
        ),
        migrations.AlterField(
            model_name='unknown',
            name='unknown_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
