# Generated by Django 2.2.5 on 2021-05-28 05:41

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210528_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 10, 19, 0, 0)),
        ),
    ]
