# Generated by Django 2.2.5 on 2021-05-30 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210528_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='img_face',
            field=models.ImageField(max_length=1023, null=True, upload_to='images/temps/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 4, 17, 0, 0)),
        ),
        migrations.AlterField(
            model_name='unknown',
            name='img_face',
            field=models.ImageField(max_length=1023, null=True, upload_to='images/temps/'),
        ),
    ]
