# Generated by Django 2.2.5 on 2021-05-28 02:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210528_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 12, 5, 0, 0)),
        ),
    ]
