# Generated by Django 2.2.5 on 2021-05-28 07:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210528_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='confidence',
            field=models.FloatField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 9, 23, 0, 0)),
        ),
        migrations.AlterField(
            model_name='unknown',
            name='confidence',
            field=models.FloatField(default=0, null=True),
        ),
    ]
