# Generated by Django 2.2.5 on 2021-05-28 07:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210528_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 7, 18, 0, 0)),
        ),
    ]
