# Generated by Django 2.2.5 on 2021-05-30 11:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210530_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 1, 18, 0, 0)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='time_slot',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
