# Generated by Django 2.2.5 on 2021-06-06 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210531_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 4, 20, 0, 0)),
        ),
    ]
