# Generated by Django 3.0.5 on 2021-05-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id_lecturer', models.IntegerField(default=100000000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
