# Generated by Django 3.0.5 on 2021-05-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(max_length=9)),
                ('name', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=30)),
            ],
        ),
    ]
