# Generated by Django 3.0.5 on 2021-05-20 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.IntegerField(default=100000000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0, null=True)),
                ('birthday', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
