# Generated by Django 3.0.5 on 2021-04-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.PositiveIntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=4)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
    ]
