# Generated by Django 3.0.5 on 2021-04-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='_id',
        ),
    ]
