# Generated by Django 3.0.5 on 2021-05-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.IntegerField(default=100000000, primary_key=True, serialize=False)),
                ('id_lecturer', models.IntegerField(default=100000000)),
                ('id_room', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
