# Generated by Django 3.0.5 on 2021-05-20 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nameSubject', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('id_lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturer.Lecturer')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
