# Generated by Django 3.0.5 on 2021-05-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id_lecturer',
            field=models.IntegerField(default=100000000, max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id_room',
            field=models.CharField(default=100000000, max_length=30),
        ),
    ]
