# Generated by Django 3.0.5 on 2021-05-20 07:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id_attendance', models.IntegerField(default=100000000, primary_key=True, serialize=False)),
                ('absent', models.CharField(max_length=30)),
                ('time', models.TimeField(default=datetime.datetime(2021, 5, 20, 14, 10, 2, 945747))),
                ('face_img', models.ImageField(null=True, upload_to='')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
